apiVersion: v1
kind: Service
metadata:
  name: tooling-web-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: tooling-web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: tooling-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tooling-db
spec:
  serviceName: {{ .Values.database.host }}
  replicas: 1
  selector:
    matchLabels:
      app: tooling-db
  template:
    metadata:
      labels:
        app: tooling-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: { name: tooling-db-secret, key: root-password }
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef: { name: tooling-db-secret, key: database }
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef: { name: tooling-db-secret, key: username }
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef: { name: tooling-db-secret, key: password }
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.database.storageSize }}