apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tooling-web
  template:
    metadata:
      labels:
        app: tooling-web
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      containers:
      - name: tooling-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "{{ .Values.database.host }}"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: tooling-db-secret
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: tooling-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tooling-db-secret
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
