# Application configuration
namespace: tooling
replicaCount: 3

image:
  repository: toolingacr.azurecr.io/tooling-web
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP   # Changed from LB Ingress controller is now the public entry point
  port: 80

# Ingress + TLS configuration
ingress:
  enabled: true
  host: heros.com.ng   # domain name i'm using

# Database configuration
database:
  host: "tooling-db-service"
  storageSize: 10Gi
  storageClass: "managed-csi"

# Monitoring toggle for Prometheus
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70