replicaCount: 3

image:
  repository: toolingacr.azurecr.io/tooling-web
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

database:
  host: "tooling-db-service"
  storageSize: 10Gi

# Monitoring toggle for Prometheus
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
