replicaCount: 3

image:
  repository: toolingacr.azurecr.io/tooling-web # Your ACR Login Server
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

database:
  host: "tooling-db-service"
  storageSize: 10Gi

# Monitoring toggle for Prometheus to find your pods
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"